### ISSUE TITLE
Integration tests fail because the private stop() method is called

### ISSUE THREAD

**Issue by magnusbaeck** [logstash-plugins/logstash-input-rabbitmq#63]
Trying to run the integration tests on commit 6af9884e, the instance.stop() call in the integration tests fail since stop() is private:

```
$ bundle exec rspec -f d
Using Accessor#strict_set for specs
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}

with a live server
  should have the correct prefetch value (FAILED - 1)
  receiving a message with a queue specified
    should process the message (FAILED - 2)
  using defaults
    should start, connect, and stop cleanly (FAILED - 3)
  LogStash::Inputs::RabbitMQ
    behaves like an interruptible input plugin
      #stop
        returns from run (FAILED - 4)

LogStash::Inputs::RabbitMQ
  when connected
    should default the codec to JSON
    #connect!
      with an exchange declared
        should bind to the exchange
        but not immediately available
          should reconnect
      without an exchange declared
        should set the prefetch value correctly
        should set the queue correctly

Failures:

  1) with a live server should have the correct prefetch value
     Failure/Error: instance.stop()
     NoMethodError:
       private method `stop' called for #<LogStash::Inputs::RabbitMQ:0x306691bb>
     # ./spec/inputs/rabbitmq_spec.rb:139:in `(root)'
     # /home/magnus/.rvm/gems/jruby-1.7.23/gems/rspec-wait-0.0.8/lib/rspec/wait.rb:46:in `(root)'

  2) with a live server receiving a message with a queue specified should process the message
     Failure/Error: instance.stop()
     NoMethodError:
       private method `stop' called for #<LogStash::Inputs::RabbitMQ:0x5c3df160>
     # ./spec/inputs/rabbitmq_spec.rb:139:in `(root)'
     # /home/magnus/.rvm/gems/jruby-1.7.23/gems/rspec-wait-0.0.8/lib/rspec/wait.rb:46:in `(root)'

  3) with a live server using defaults should start, connect, and stop cleanly
     Failure/Error: instance.stop()
     NoMethodError:
       private method `stop' called for #<LogStash::Inputs::RabbitMQ:0x759c3036>
     # ./spec/inputs/rabbitmq_spec.rb:139:in `(root)'
     # /home/magnus/.rvm/gems/jruby-1.7.23/gems/rspec-wait-0.0.8/lib/rspec/wait.rb:46:in `(root)'

  4) with a live server LogStash::Inputs::RabbitMQ behaves like an interruptible input plugin #stop returns from run
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       private method `stop' called for #<LogStash::Inputs::RabbitMQ:0x16cfb761>
     Shared Example Group: "an interruptible input plugin" called from ./spec/inputs/rabbitmq_spec.rb:170
     # ./spec/inputs/rabbitmq_spec.rb:139:in `(root)'
     # /home/magnus/.rvm/gems/jruby-1.7.23/gems/rspec-wait-0.0.8/lib/rspec/wait.rb:46:in `(root)'

Finished in 6.39 seconds (files took 4 seconds to load)
9 examples, 4 failures

Failed examples:

rspec ./spec/inputs/rabbitmq_spec.rb:150 # with a live server should have the correct prefetch value
rspec ./spec/inputs/rabbitmq_spec.rb:158 # with a live server receiving a message with a queue specified should process the message
rspec ./spec/inputs/rabbitmq_spec.rb:145 # with a live server using defaults should start, connect, and stop cleanly
rspec /home/magnus/.rvm/gems/jruby-1.7.23/gems/logstash-devutils-0.0.18-java/lib/logstash/devutils/rspec/shared_examples.rb:9 # with a live server LogStash::Inputs::RabbitMQ behaves like an interruptible input plugin #stop returns from run

Randomized with seed 25863
```

I doubt it's related, but I wasn't sure how to run the integration tests (since they're under a `:integration => true` condition) so I monkey-patched that line like so:

```
-describe "with a live server", :integration => true do
+describe "with a live server" do
```

I occasionally get the tests to pass if I comment out the stop() call, but they seem generally flaky and in need of some love.

**Comment by jsvd** [comment]
strange, I haven't been able to make them fail yet, even with your seed:

```
logstash-input-rabbitmq (git)-[master] % bundle exec rspec -s 25863
Using Accessor#strict_set for specs
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}
.....

Finished in 1.24 seconds (files took 2.26 seconds to load)
5 examples, 0 failures

Randomized with seed 25863
```

**Comment by magnusbaeck** [comment]
Oh, that's weird. To me the error looks like a clear-cut coding error. Could there be a difference in e.g. JRuby version? This is what I run:

```
$ jruby --version
jruby 1.7.23 (1.9.3p551) 2015-11-24 f496dd5 on OpenJDK 64-Bit Server VM 1.7.0_91-b02 +jit [linux-amd64]
```

**Comment by jsvd** [comment]
humm I don't see why it should be private..https://github.com/logstash-plugins/logstash-input-rabbitmq/blob/6af9884e8aed042ba62aab460322bb885e509ae4/lib/logstash/inputs/rabbitmq.rb#L107-L111

I'm using jruby 1.7.22. I'll upgrade just to double check but shouldn't make a difference

**Comment by magnusbaeck** [comment]
Indeed, JRuby shouldn't matter and the original definition of stop() (AFAIK anyway—[logstash/inputs/base.rb:70](https://github.com/elastic/logstash/blob/d74d41cb30c327ddb658e9b51fc2b2206a3d59fb/logstash-core/lib/logstash/inputs/base.rb#L70-L77)) is also public.

But wait... I don't think you enabled the integration tests? Your log output indicates that you only ran 5 tests, but with integration tests enabled I believe it should've said 9 tests.

Anyway, I recloned the git and retried and things just worked. Maybe my original work directory was broken somehow. I'll do some digging and close the issue if this indeed was a false alarm. Sorry.

**Comment by jsvd** [comment]
I did experiment with running integration tests and  they also worked :/

**Comment by magnusbaeck** [comment]
Oh dear. Giant facepalm for me and a testament to my Ruby ignorance. I had added a couple of private methods and wasn't aware that prepending a method definition with `private` apparently affects the rest of the class except those explicitly marked `public`. And, you guessed it, `def stop` happened to follow my private methods. Closing the issue, obviously, and sorry for taking your time.

What convention do you guys use for private methods in the Logstash code? Skip the implied `public` modifier until the first private method is added?
